name: Godot CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Godot
      uses: docker://barichello/godot-ci:3.5.1
      with:
        export_templates: Linux/X11
        export_dir: export
    
    - name: Build Docker image
      run: |
        docker build -t sale955/godhit:test .
      working-directory: ${{ github.workspace }}/export/Linux/X11

    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push sale955/godhit:test
