name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.5.2
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: 'docker.io'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Godot Engine
      uses: pascalineo/godot-engine-action@v1
      with:
        version: ${{ env.GODOT_VERSION }}
        export: 'templates/linux_x11.64'

    - name: Export Godot game for Linux
      run: |
        mkdir -p export/linux
        godot --path ./project --export "Linux/X11" "../export/linux/game.x86_64"
    - name: Build and publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:3.5.1
        secrets: |
          DOCKER_USERNAME=${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD=${{ env.DOCKER_PASSWORD }}
      env:
        GAME_FILE: './export/linux/game.x86_64'
