name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: test-project
  PROJECT_PATH: test-project
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Install Docker
        run: |
           sudo apt-get update
           sudo apt-get install -y docker.io
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/$EXPORT_NAME:$GODOT_VERSION -f Dockerfile .
      - name: Push Docker Image
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - run: |
          docker push $DOCKER_USERNAME/$EXPORT_NAME:$GODOT_VERSION
