name: "godot-ci export"

on:
  push:
    branches:
      - dev

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: test-project
  PROJECT_PATH: test-project
  DOCKER_IMAGE_NAME: sale955/godhit

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:$GODOT_VERSION .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $DOCKER_IMAGE_NAME:$GODOT_VERSION
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          docker run --rm -v $(pwd):/src $DOCKER_IMAGE_NAME:$GODOT_VERSION bash -c 'godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64'
